#!/bin/bash
IntegerCheck() {
[[ "$1" =~ ^[1-9]+$ ]]
}
read -p "Enter the number of elements of the array: " N
while ! IntegerCheck "$N" || [ "$N" -lt 0 ]; do
echo "Error: Please enter a positive number"
read -p "Enter the number of elements once again: " N
done
numbers=()
sum=0
for (( i=1 ; i<=N ; i++ )); do
while true; do
read -p "Enter element number "$i": " num
if IntegerCheck "$num"; then
numbers+=($num)
break
else
echo "Error: please enter a valid number"
fi
done
done
for num in "${numbers[@]}"; do
sum=$(( sum+num ))
done
echo "Array: ${numbers[@]}"
echo "The Summation of Array elements equals to: $sum"
